'use client';
import { useEffect, useState } from 'react';
type Panel = 'rules' | 'testimonials' | 'users';
export default function AdminDashboard({ role, email }: { role: string; email: string }) {
  const [panel, setPanel] = useState<Panel>('rules'); const [status, setStatus] = useState('pending'); const [data, setData] = useState<any>(null); const [items, setItems] = useState<any[]>([]);
  const load = async () => { const overview = await fetch('/api/admin/overview'); if (overview.ok) setData(await overview.json()); const endpoint = panel === 'rules' ? `/api/admin/rules?status=${status}` : panel === 'testimonials' ? `/api/admin/testimonials?status=${status}` : '/api/admin/users'; const response = await fetch(endpoint); if (response.ok) { const json = await response.json(); setItems(json.rules || json.testimonials || json.users || []); } };
  useEffect(() => { load(); }, [panel, status]);
  const review = async (item: any, value: string) => { const endpoint = panel === 'rules' ? '/api/admin/rules' : '/api/admin/testimonials'; await fetch(endpoint, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...item, id: String(item.id), ...(panel === 'rules' ? { review_status: value } : { status: value }) }) }); load(); };
  const changeRole = async (item: any, value: string) => { await fetch('/api/admin/users', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ id: item.id, role: value }) }); load(); };
  return <main className="admin-shell"><header className="admin-head"><div><span className="eyebrow">PASSPORTLY / BACK-OFFICE</span><h1>Contrôle des données</h1><p>{email} · rôle {role}</p></div><a href="/">Retour au site ↗</a></header>{!data ? <p>Chargement…</p> : <><section className="admin-stats"><article><small>RÈGLES</small><strong>{data.stats.rules}</strong></article><article><small>À VALIDER</small><strong>{data.stats.pending}</strong></article><article><small>SOURCES</small><strong>{data.sources.length}</strong></article></section><nav className="admin-tabs"><button onClick={() => setPanel('rules')}>Règles</button><button onClick={() => setPanel('testimonials')}>Témoignages</button>{role === 'admin' && <button onClick={() => setPanel('users')}>Utilisateurs</button>}</nav><section className="admin-grid"><div className="admin-card"><div className="admin-card-head"><h2>{panel === 'rules' ? 'Validation humaine' : panel === 'testimonials' ? 'Modération' : 'Rôles et permissions'}</h2>{panel !== 'users' && <select value={status} onChange={e => setStatus(e.target.value)}><option value="pending">À traiter</option><option value="approved">Validés</option><option value="rejected">Rejetés</option></select>}</div>{items.map(item => <article className="rule-row" key={item.id}><div><b>{panel === 'rules' ? `${item.passport_code} → ${item.destination_code}` : item.email || `${item.author_name} · ${item.destination}`}</b><span>{panel === 'rules' ? `${item.requirement}${item.max_stay_days ? ` · ${item.max_stay_days} jours` : ''}` : item.content || item.role}</span><small>{item.source_name || item.author_email || ''}</small></div><div className="rule-actions">{panel === 'users' ? <select value={item.role} onChange={e => changeRole(item, e.target.value)}><option value="user">user</option><option value="editor">editor</option><option value="admin">admin</option></select> : <><button onClick={() => review(item, 'approved')}>Valider</button><button className="reject" onClick={() => review(item, 'rejected')}>Rejeter</button></>}</div></article>)}</div><aside><div className="admin-card"><h2>Sources</h2>{data.sources.map((s: any) => <p className="source-row" key={s.source_name}><b>{s.source_name}</b><span>{s.count} règles</span></p>)}</div><div className="admin-card"><h2>Journal d’audit</h2>{data.audit.slice(0, 8).map((a: any) => <p className="audit-row" key={a.id}><b>{a.action}</b> · {a.entity_type}<small>{a.email || 'système'}</small></p>)}</div></aside></section></>}</main>;
}
