'use client';

import Link from 'next/link';
import { FormEvent, MouseEvent, useEffect, useState } from 'react';

type User = { id: number; email: string };
type Saved = { id: number; passport_code: string; destination_code: string; created_at: string };
type Alert = { id: number; passport_code: string; destination_code: string | null; email_enabled: boolean; created_at: string };

async function request<T>(url: string, options?: RequestInit): Promise<T> {
  const response = await fetch(url, { ...options, headers: { 'Content-Type': 'application/json', ...(options?.headers || {}) } });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body.error || 'Une erreur est survenue.');
  return body;
}

function Header({ user, onLogout }: { user: User | null; onLogout: () => void }) {
  return <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">P</span><span>passportly</span></Link><nav><Link href="/">Explorer</Link><a href="/#guides">Guides</a><a href="/#comparer">Comparer</a><a href="/#api">API</a></nav><div className="top-actions"><span className="language">FR <span>⌄</span></span>{user ? <button className="login" onClick={onLogout}>Se déconnecter</button> : <Link className="login" href="/account">Se connecter</Link>}<button className="menu">☰</button></div></header>;
}

function AuthForm({ onAuthenticated }: { onAuthenticated: (user: User) => void }) {
  const [mode, setMode] = useState<'login' | 'register'>('login');
  const [email, setEmail] = useState(''); const [password, setPassword] = useState('');
  const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); setLoading(true); try { const result = await request<{ user: User }>(`/api/auth/${mode}`, { method: 'POST', body: JSON.stringify({ email, password }) }); onAuthenticated(result.user); } catch (err) { setError(err instanceof Error ? err.message : 'Impossible de se connecter.'); } finally { setLoading(false); } }
  return <section className="account-auth"><span className="eyebrow">ESPACE PERSONNEL</span><h1>{mode === 'login' ? 'Bon retour.' : 'Créer votre compte.'}</h1><p>Retrouvez vos destinations enregistrées et recevez les changements importants.</p><div className="auth-tabs"><button className={mode === 'login' ? 'active' : ''} onClick={() => setMode('login')}>Se connecter</button><button className={mode === 'register' ? 'active' : ''} onClick={() => setMode('register')}>Créer un compte</button></div><form onSubmit={submit} className="account-form"><label>Email<input type="email" value={email} onChange={e => setEmail(e.target.value)} required autoComplete="email" placeholder="vous@exemple.com" /></label><label>Mot de passe<input type="password" value={password} onChange={e => setPassword(e.target.value)} required minLength={8} autoComplete={mode === 'login' ? 'current-password' : 'new-password'} placeholder="8 caractères minimum" /></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="primary" disabled={loading}>{loading ? 'Connexion…' : mode === 'login' ? 'Ouvrir mon espace →' : 'Créer mon compte →'}</button></form></section>;
}

export default function AccountPanel() {
  const [user, setUser] = useState<User | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [saved, setSaved] = useState<Saved[]>([]); const [alerts, setAlerts] = useState<Alert[]>([]); const [passport, setPassport] = useState('CM'); const [destination, setDestination] = useState(''); const [alertDestination, setAlertDestination] = useState(''); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState('');
  async function load(userValue: User) { const [savedResult, alertResult] = await Promise.all([request<{ data: Saved[] }>('/api/account/saved'), request<{ data: Alert[] }>('/api/account/alerts')]); setUser(userValue); setSaved(savedResult.data); setAlerts(alertResult.data); }
  useEffect(() => { request<{ user: User | null }>('/api/auth/me').then(result => result.user ? load(result.user) : null).catch(() => setError('Impossible de vérifier la session.')).finally(() => setLoading(false)); }, []);
  async function logout() { await request('/api/auth/logout', { method: 'POST' }); setUser(null); setSaved([]); setAlerts([]); setNotice('Vous êtes déconnecté.'); }
  async function addSaved(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { const result = await request<{ data: Saved }>('/api/account/saved', { method: 'POST', body: JSON.stringify({ passport, destination }) }); if (result.data) setSaved(current => [result.data, ...current]); setDestination(''); setNotice('Destination ajoutée à vos favoris.'); } catch (err) { setError(err instanceof Error ? err.message : 'Impossible d’ajouter ce favori.'); } finally { setBusy(false); } }
  async function removeSaved(item: Saved) { try { await request('/api/account/saved', { method: 'DELETE', body: JSON.stringify({ passport: item.passport_code, destination: item.destination_code }) }); setSaved(current => current.filter(value => value.id !== item.id)); setNotice('Favori supprimé.'); } catch (err) { setError(err instanceof Error ? err.message : 'Impossible de supprimer ce favori.'); } }
  async function addAlert(event: FormEvent) { event.preventDefault(); setBusy(true); try { const result = await request<{ data: Alert }>('/api/account/alerts', { method: 'POST', body: JSON.stringify({ passport, destination: alertDestination || null }) }); setAlerts(current => [result.data, ...current]); setAlertDestination(''); setNotice('Alerte activée.'); } catch (err) { setError(err instanceof Error ? err.message : 'Impossible d’activer cette alerte.'); } finally { setBusy(false); } }
  async function disableAlert(item: Alert | MouseEvent<HTMLButtonElement>) { if (!('id' in item)) return; try { await request('/api/account/alerts', { method: 'DELETE', body: JSON.stringify({ id: item.id }) }); setAlerts(current => current.filter(value => value.id !== item.id)); setNotice('Alerte désactivée.'); } catch (err) { setError(err instanceof Error ? err.message : 'Impossible de désactiver cette alerte.'); } }
  if (loading) return <main><Header user={null} onLogout={logout} /><div className="account-state">Chargement de votre espace…</div></main>;
  return <main><Header user={user} onLogout={logout} />{!user ? <><AuthForm onAuthenticated={value => load(value).catch(err => setError(err.message))} />{notice && <p className="account-notice">{notice}</p>}</> : <section className="account-page"><div className="account-heading"><div><span className="eyebrow">MON ESPACE</span><h1>Bonjour, {user.email}</h1><p>Vos voyages suivis, au même endroit.</p></div><button className="outline" onClick={logout}>Se déconnecter</button></div>{(error || notice) && <p className={error ? 'form-error' : 'account-notice'} role="status">{error || notice}</p>}<div className="account-grid"><article className="account-card"><div className="card-heading"><div><span className="eyebrow">DESTINATIONS</span><h2>Mes favoris</h2></div><span className="card-count">{saved.length}</span></div><form className="inline-form" onSubmit={addSaved}><input value={passport} onChange={e => setPassport(e.target.value.toUpperCase())} maxLength={2} aria-label="Code du passeport" placeholder="CM" /><input value={destination} onChange={e => setDestination(e.target.value.toUpperCase())} maxLength={2} required aria-label="Code de destination" placeholder="FR" /><button className="primary compact" disabled={busy}>Ajouter</button></form>{saved.length ? <ul className="account-list">{saved.map(item => <li key={item.id}><span className="country-code">{item.destination_code}</span><div><b>{item.passport_code} → {item.destination_code}</b><small>Destination enregistrée</small></div><button className="delete-button" onClick={() => removeSaved(item)} aria-label={`Supprimer ${item.destination_code}`}>Supprimer</button></li>)}</ul> : <p className="empty">Aucun favori pour le moment. Ajoutez un code de destination ci-dessus.</p>}</article><article className="account-card"><div className="card-heading"><div><span className="eyebrow">VEILLE</span><h2>Mes alertes</h2></div><span className="card-count">{alerts.length}</span></div><form className="inline-form" onSubmit={addAlert}><input value={alertDestination} onChange={e => setAlertDestination(e.target.value.toUpperCase())} maxLength={2} aria-label="Code de destination pour l'alerte" placeholder="FR (optionnel)" /><button className="primary compact" disabled={busy}>Activer</button></form>{alerts.length ? <ul className="account-list">{alerts.map(item => <li key={item.id}><span className="alert-status">●</span><div><b>{item.passport_code}{item.destination_code ? ` → ${item.destination_code}` : ' · toutes destinations'}</b><small>{item.email_enabled ? 'Alerte email active' : 'Alerte désactivée'}</small></div><button className="delete-button" onClick={disableAlert}>Désactiver</button></li>)}</ul> : <p className="empty">Aucune alerte active. Soyez prévenu quand une règle évolue.</p>}<p className="card-help">Les codes pays utilisent le format ISO à deux lettres, par exemple CM ou FR.</p></article></div></section>}</main>;
}
