'use client';
import { useState } from 'react';
import { ItineraryPlanner } from '../itinerary/ItineraryPlanner';

export function ProductPanels({ tab }: { tab: string }) {
  const [left, setLeft] = useState('CM'); const [right, setRight] = useState('FR');
  const [compare, setCompare] = useState<Record<string, unknown>[] | null>(null);
  const [days, setDays] = useState(''); const [result, setResult] = useState<{ usedDays?: number; remainingDays?: number; compliant?: boolean } | null>(null);
  if (tab === 'Explorer') return null;
  const runCompare = async () => { const response = await fetch(`/api/compare?left=${left}&right=${right}`); const json = await response.json(); setCompare(json.data || []); };
  const runSchengen = async () => { const response = await fetch('/api/schengen', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ entries: days ? [{ start: '2026-01-01', end: `2026-01-${days.padStart(2, '0')}` }] : [] }) }); setResult(await response.json()); };
  return <section className="product-panel"><div className="product-panel-inner">{tab === 'Guides' && <ItineraryPlanner />}
    {tab === 'Comparer' && <><span className="eyebrow">COMPARATEUR DE MOBILITÉ</span><h2>Deux passeports. Une vision claire.</h2><p>Compare les règles d’accès par destination, avec les mêmes sources et dates de vérification.</p><div className="panel-form"><label>Passeport A<input value={left} onChange={e => setLeft(e.target.value.toUpperCase())} maxLength={2} /></label><span>↔</span><label>Passeport B<input value={right} onChange={e => setRight(e.target.value.toUpperCase())} maxLength={2} /></label><button className="primary compact" onClick={runCompare}>Comparer <span>→</span></button></div>{compare && <div className="compare-results"><b>{compare.length} destinations comparées</b><div className="compare-scroll">{compare.slice(0, 12).map((row, index) => <div className="compare-row" key={String(row.destination || index)}><span>{String(row.destination)}</span><small>{String((row[left] as { requirement?: string })?.requirement || '—')} · {String((row[right] as { requirement?: string })?.requirement || '—')}</small></div>)}</div></div>}</>}
    {tab === 'Guides' && <><span className="eyebrow">GUIDES DE PRÉPARATION</span><h2>Préparer son dossier, sans zone grise.</h2><p>Des parcours clairs pour les destinations qui demandent le plus d’anticipation.</p><div className="guide-list">{['Schengen depuis le Cameroun','Visa Canada : documents et délais','Étudier en France','Voyager à Dubaï','Turquie : e-visa ou consulat'].map((title, index) => <article key={title}><span className="guide-number">0{index + 1}</span><div><b>{title}</b><small>Documents · étapes · frais · sources officielles</small></div><span>↗</span></article>)}</div><div className="schengen-box"><div><span className="eyebrow">OUTIL GRATUIT</span><h3>Calculateur Schengen 90 / 180</h3><p>Indique le nombre de jours déjà passés dans l’espace Schengen.</p></div><div className="schengen-input"><input value={days} onChange={e => setDays(e.target.value.replace(/\D/g, '').slice(0, 2))} placeholder="0" /><span>jours utilisés</span><button onClick={runSchengen}>Calculer</button>{result && <b className={result.compliant ? 'ok' : 'danger'}>{result.remainingDays} jours restants</b>}</div></div></>}
    {tab === 'API' && <><span className="eyebrow">POUR LES DÉVELOPPEURS</span><h2>Les règles de visa, dans vos produits.</h2><p>Une API documentée, avec la source, la date de vérification et le niveau de confiance de chaque règle.</p><div className="api-grid"><article><b>Free</b><strong>1 000</strong><small>requêtes / mois</small><button>Commencer</button></article><article className="api-highlight"><b>Pro</b><strong>10 000</strong><small>requêtes / mois · 29 €</small><button>Choisir Pro</button></article><article><b>Business</b><strong>Illimité</strong><small>support et widgets · 199 €</small><button>Nous contacter</button></article></div><pre className="code-block">{`GET /api/visa?passport=CM&destination=FR\n\n{\n  "requirement": "visa_required",\n  "source_url": "...",\n  "confidence": "dataset"\n}`}</pre></>}
  </div></section>;
}
