'use client';
import { useState } from 'react';
type Stay = { start: string; end: string; country: string };
type Result = { usedDays: number; remainingDays: number; overstayDays: number; compliant: boolean; estimatedFees: number; daysByCountry: Record<string, number>; checklist: string[] };
export function ItineraryPlanner() {
  const [stays, setStays] = useState<Stay[]>([{ start: '2026-10-01', end: '2026-10-15', country: 'France' }]); const [referenceDate, setReferenceDate] = useState('2026-10-15'); const [result, setResult] = useState<Result | null>(null); const [error, setError] = useState('');
  const update = (index: number, key: keyof Stay, value: string) => setStays(items => items.map((item, i) => i === index ? { ...item, [key]: value } : item));
  const calculate = async () => { setError(''); const response = await fetch('/api/itinerary', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ stays, referenceDate }) }); const json = await response.json(); if (!response.ok) setError(json.error); else setResult(json); };
  return <div className="itinerary-planner"><div className="itinerary-head"><div><span className="eyebrow">PLANIFICATEUR MULTI-PAYS</span><h3>Votre calendrier Schengen, au jour près.</h3><p>Ajoutez chaque séjour : les chevauchements sont comptés une seule fois dans la fenêtre glissante 90 / 180.</p></div><label>Date de contrôle<input type="date" value={referenceDate} onChange={e => setReferenceDate(e.target.value)} /></label></div><div className="stay-list">{stays.map((stay, index) => <div className="stay-row" key={index}><span className="stay-number">0{index + 1}</span><label>Pays<input value={stay.country} onChange={e => update(index, 'country', e.target.value)} /></label><label>Arrivée<input type="date" value={stay.start} onChange={e => update(index, 'start', e.target.value)} /></label><label>Départ<input type="date" value={stay.end} onChange={e => update(index, 'end', e.target.value)} /></label><button aria-label="Supprimer le séjour" onClick={() => setStays(items => items.filter((_, i) => i !== index))}>×</button></div>)}</div><div className="itinerary-actions"><button className="outline" onClick={() => setStays(items => [...items, { start: '2026-10-16', end: '2026-10-20', country: '' }])}>+ Ajouter un pays</button><button className="primary compact" onClick={calculate}>Calculer l’itinéraire <span>→</span></button></div>{error && <p className="itinerary-error">{error}</p>}{result && <div className="itinerary-result"><div className={result.compliant ? 'result-status ok' : 'result-status danger'}><b>{result.compliant ? 'Séjour conforme' : `Dépassement de ${result.overstayDays} jour(s)`}</b><span>{result.usedDays} jours utilisés · {result.remainingDays} restants</span></div><div className="result-grid"><div><small>FRAIS ESTIMÉS</small><b>{result.estimatedFees} €</b></div><div><small>PAR PAYS</small><b>{Object.entries(result.daysByCountry).map(([country, days]) => `${country} ${days}j`).join(' · ')}</b></div></div><div className="checklist"><small>CHECKLIST GLOBALE</small>{result.checklist.map(item => <span key={item}>✓ {item}</span>)}</div></div>}</div>;
}
