import { NextResponse } from 'next/server';
const code = { type: 'string', minLength: 2, maxLength: 2, pattern: '^[A-Za-z]{2}$' };
const common = { '401': { description: 'Invalid API key' }, '429': { description: 'Hourly quota exceeded' }, '500': { description: 'Internal error' } };
export async function GET() { return NextResponse.json({ openapi: '3.0.3', info: { title: 'Passportly Developer API', version: '1.0.0', description: 'Visa data API. Quotas are hourly.' }, servers: [{ url: '/api' }], security: [{ apiKey: [] }], components: { securitySchemes: { apiKey: { type: 'apiKey', in: 'header', name: 'x-api-key' }, bearer: { type: 'http', scheme: 'bearer' } }, schemas: { Error: { type: 'object', required: ['error'], properties: { error: { type: 'object', required: ['code','message'], properties: { code: { type: 'string' }, message: { type: 'string' }, details: { type: 'object', additionalProperties: true } } } } }, Meta: { type: 'object', properties: { requestId: { type: 'string' }, plan: { type: 'string' }, quota: { type: 'integer' }, version: { type: 'string' } } } } }, paths: {
    '/v1/visa': { get: { operationId: 'visa', parameters: [{ name: 'passport', in: 'query', required: true, schema: code }, { name: 'destination', in: 'query', schema: code }], responses: { '200': { description: 'Visa rules with source metadata' }, '400': { description: 'Invalid parameter' }, ...common } } },
    '/v1/map': { get: { operationId: 'map', parameters: [{ name: 'passport', in: 'query', required: true, schema: code }], responses: { '200': { description: 'Destination rules' }, '400': { description: 'Invalid parameter' }, ...common } } },
    '/v1/compare': { get: { operationId: 'compare', parameters: [{ name: 'left', in: 'query', required: true, schema: code }, { name: 'right', in: 'query', required: true, schema: code }], responses: { '200': { description: 'Comparison' }, '400': { description: 'Invalid parameter' }, ...common } } },
    '/v1/countries': { get: { operationId: 'countries', responses: { '200': { description: 'Countries' }, ...common } } },
    '/v1/guides': { get: { operationId: 'guides', parameters: [{ name: 'slug', in: 'query', schema: { type: 'string' } }], responses: { '200': { description: 'Guides' }, ...common } } }
  } }); }
