'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Flag } from '../shared/ui/Flag';
import { ProductPanels } from './components/ProductPanels';

type Destination={code:string;name:string;status:string;requirement:string;days:string;color:string;source?:string;sourceUrl?:string;sourceQuality?:string;checked?:string;confidence?:string};
const filters=[['all','Toutes'],['visa_free','Sans visa'],['evisa','eVisa'],['visa_on_arrival','À l’arrivée'],['visa_required','Visa requis']];
function DestinationCard({d,onOpen}:{d:Destination;onOpen:()=>void}){return <button className="destination-card" onClick={onOpen}><span className="card-flag"><Flag code={d.code} fallback={d.code.toUpperCase()}/></span><span className="card-copy"><strong>{d.name}</strong><small>{d.status}</small><em>{d.days}</em></span><span className={'status-dot '+d.color}/></button>}
export default function Home(){
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[view,setView]=useState<'map'|'list'>('map'),[tab,setTab]=useState('Explorer'),[countries,setCountries]=useState<Destination[]>([]),[selected,setSelected]=useState<Destination|null>(null),[loading,setLoading]=useState(true);
 useEffect(()=>{const c=new AbortController();setLoading(true);fetch(`/api/countries?passport=CM&requirement=${filter}&search=${encodeURIComponent(query)}`,{signal:c.signal}).then(r=>r.json()).then(j=>setCountries(j.data||[])).catch(()=>{}).finally(()=>setLoading(false));return()=>c.abort()},[filter,query]);
 return <main className="site-shell">
  <header className="new-header"><Link href="/" className="new-brand"><span>P</span><b>passportly</b></Link><nav>{['Explorer','Guides','Comparer','API'].map(item=><button key={item} onClick={()=>setTab(item)} className={tab===item?'active':''}>{item}</button>)}</nav><div className="header-end"><button className="locale">FR <span>⌄</span></button><Link href="/account" className="account-link">Mon espace <span>↗</span></Link></div></header>
  {tab!=='Explorer'&&<ProductPanels tab={tab}/>}
  <section className="new-hero"><div className="hero-label"><span/> PASSPORTLY / EXPLORER LE MONDE</div><div className="hero-grid"><div><h1>Voyager commence<br/><i>par savoir.</i></h1><p>Les règles de visa, expliquées simplement. Pour votre passeport, votre destination et votre prochain départ.</p><div className="hero-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher une destination"/><kbd>⌘ K</kbd></div><div className="selected-passport"><Flag code="cm" fallback="CM" size={24}/><span><small>Votre passeport</small><strong>Cameroun</strong></span><button>Changer</button></div></div><div className="hero-aside"><div className="route-line"><span>CM</span><b>→</b><span>?</span></div><p>Une destination en tête ?<br/><strong>Voyez ce qu’il vous faut.</strong></p><div className="hero-stat"><strong>38 612</strong><span>règles référencées<br/>et sourcées</span></div></div></div></section>
  <section className="trust-strip"><div><strong>198</strong><span>passeports</span></div><div><strong>227</strong><span>destinations</span></div><div><strong>100%</strong><span>traçables</span></div><p>Chaque règle possède une date, un niveau de confiance et une référence.</p></section>
  <section className="explorer-section"><div className="section-intro"><div><span className="section-kicker">01 / MOBILITÉ</span><h2>Où pouvez-vous aller ?</h2></div><div className="view-switch"><button className={view==='map'?'active':''} onClick={()=>setView('map')}>Vue carte</button><button className={view==='list'?'active':''} onClick={()=>setView('list')}>Vue liste</button></div></div><div className="filter-row">{filters.map(([key,label])=><button key={key} onClick={()=>setFilter(key)} className={filter===key?'active':''}>{label}</button>)}</div>{loading?<div className="loading-card">Recherche des règles de voyage…</div>:view==='list'?<div className="destination-list">{countries.map(d=><DestinationCard key={d.code} d={d} onOpen={()=>setSelected(d)}/>)}</div>:<div className="explorer-grid"><div className="atlas"><div className="atlas-toolbar"><span>Depuis <b>Cameroun</b></span><div><button>−</button><button>＋</button></div></div><div className="atlas-shape shape-one"/><div className="atlas-shape shape-two"/>{countries.slice(0,12).map((d,i)=><button key={d.code} className={'atlas-pin '+d.color} style={{left:`${16+(i*23)%70}%`,top:`${25+(i*31)%52}%`}} onClick={()=>setSelected(d)}><Flag code={d.code} fallback={d.code.toUpperCase()}/><small>{d.name}</small></button>)}<div className="atlas-key"><span><i className="green"/> Facile</span><span><i className="blue"/> En ligne</span><span><i className="amber"/> À préparer</span></div></div><aside className="popular-panel"><div className="panel-heading"><span>DESTINATIONS EN VUE</span><button onClick={()=>setView('list')}>Tout voir ↗</button></div>{countries.slice(0,5).map(d=><DestinationCard key={d.code} d={d} onOpen={()=>setSelected(d)}/>)}<Link href="/account" className="panel-cta"><span>+</span><b>Enregistrer une destination</b><em>→</em></Link></aside></div>}</section>
  <section className="next-section"><div><span className="section-kicker">02 / PRÉPARATION</span><h2>Moins de flou.<br/><i>Plus de départs.</i></h2></div><div className="next-cards"><Link href="/guides" className="next-card coral"><span>↗</span><small>GUIDES</small><strong>Comprendre<br/>les démarches.</strong><em>Explorer les guides</em></Link><Link href="/itinerary" className="next-card lilac"><span>◷</span><small>ITINÉRAIRE</small><strong>Planifier un séjour<br/>sans mauvaise surprise.</strong><em>Ouvrir le planificateur</em></Link><Link href="/developer" className="next-card dark"><span>⌘</span><small>POUR LES ÉQUIPES</small><strong>Les données utiles<br/>dans vos produits.</strong><em>Voir l’API</em></Link></div></section>
  <footer className="new-footer"><Link href="/" className="new-brand"><span>P</span><b>passportly</b></Link><p>La clarté avant le départ.</p><div><Link href="/data-policy">Données</Link><Link href="/legal">À propos</Link><Link href="/account">Mon espace</Link></div></footer>
  {selected&&<div className="new-modal-backdrop" onClick={()=>setSelected(null)}><section className="new-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSelected(null)}>×</button><div className="modal-country"><Flag code={selected.code} fallback={selected.code.toUpperCase()} size={44}/><div><span>DEPUIS LE CAMEROUN · {selected.code.toUpperCase()}</span><h2>{selected.name}</h2></div></div><div className={'modal-status '+selected.color}><strong>{selected.status}</strong><span>{selected.days} · mise à jour le {selected.checked||'date non renseignée'}</span></div><div className="modal-details"><div><small>À RETENIR</small><p>Vérifiez toujours les conditions auprès de l’autorité compétente avant le départ.</p><p>Règle synchronisée depuis PostgreSQL.</p></div><div><small>QUALITÉ DE LA SOURCE</small><strong className={selected.sourceQuality==='official'?'official':'pending'}>{selected.sourceQuality==='official'?'Source officielle':'Référence dataset'}</strong><p>{selected.source||'Source officielle à confirmer'}</p></div></div><div className="modal-reference">Référence : <b>{selected.source||'Source officielle à confirmer'}</b>{selected.sourceUrl&&<a href={selected.sourceUrl} target="_blank" rel="noreferrer">Ouvrir la référence ↗</a>}</div></section></div>}
 </main>;
}
