'use client';

import { useMemo, useState } from 'react';

type Destination = { name: string; flag: string; status: string; days: string; color: string; source: string; checked: string; confidence: string; fee: string; steps: string[] };
const destinations: Destination[] = [
  { name: 'Rwanda', flag: '🇷🇼', status: 'Visa à l’arrivée', days: '30 jours', color: 'green', source: 'Immigration Rwanda', checked: '12 sept. 2026', confidence: 'Vérifié', fee: '50 USD', steps: ['Remplir la demande en ligne', 'Préparer passeport valide 6 mois', 'Payer à l’arrivée'] },
  { name: 'Kenya', flag: '🇰🇪', status: 'eTA obligatoire', days: '90 jours', color: 'blue', source: 'eCitizen Kenya', checked: '10 sept. 2026', confidence: 'Vérifié', fee: '35 USD', steps: ['Créer son compte eCitizen', 'Téléverser photo et réservation', 'Attendre 3 jours ouvrés'] },
  { name: 'Turquie', flag: '🇹🇷', status: 'Visa requis', days: '90 jours', color: 'red', source: 'Ministère turc des Affaires étrangères', checked: '08 sept. 2026', confidence: 'Vérifié', fee: '60–100 EUR', steps: ['Prendre rendez-vous au consulat', 'Préparer relevés bancaires et assurance', 'Déposer le dossier en personne'] },
  { name: 'France / Schengen', flag: '🇫🇷', status: 'Visa requis', days: '90 / 180 jours', color: 'red', source: 'France-Visas', checked: '14 sept. 2026', confidence: 'Vérifié', fee: '90 EUR + service', steps: ['Remplir France-Visas', 'Réserver un créneau TLScontact', 'Biométrie et dépôt du dossier'] },
  { name: 'Émirats arabes unis', flag: '🇦🇪', status: 'Visa requis', days: '30 jours', color: 'amber', source: 'UAE Government Portal', checked: '05 sept. 2026', confidence: 'Communauté + source', fee: '70–150 USD', steps: ['Passer par un sponsor ou une agence', 'Fournir passeport et photo', 'Recevoir le visa par email'] },
  { name: 'Maroc', flag: '🇲🇦', status: 'Visa requis', days: '90 jours', color: 'amber', source: 'Accès Maroc / consulat', checked: '02 sept. 2026', confidence: 'À confirmer', fee: '30 EUR', steps: ['Vérifier le consulat compétent', 'Préparer justificatif d’hébergement', 'Déposer la demande'] },
];

function Icon({ children }: { children: React.ReactNode }) { return <span className="icon">{children}</span>; }

export default function Home() {
  const [query, setQuery] = useState(''); const [selected, setSelected] = useState<Destination | null>(null); const [tab, setTab] = useState('Explorer'); const [saved, setSaved] = useState(false);
  const filtered = useMemo(() => destinations.filter(d => d.name.toLowerCase().includes(query.toLowerCase())), [query]);
  return <main>
    <header className="topbar"><div className="brand"><span className="brand-mark">P</span><span>passportly</span></div><nav>{['Explorer','Guides','Comparer','API'].map(item => <button key={item} className={tab === item ? 'active' : ''} onClick={() => setTab(item)}>{item}</button>)}</nav><div className="top-actions"><button className="language">FR <span>⌄</span></button><button className="login">Se connecter</button><button className="menu">☰</button></div></header>
    <section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="pulse" /> DONNÉES VÉRIFIÉES, VOYAGES ÉCLAIRÉS</div><h1>Le monde est grand.<br /><em>Votre passeport aussi.</em></h1><p>Comprenez les règles, préparez vos documents et partez avec une longueur d’avance.</p><div className="searchbar"><span>⌕</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Où voulez-vous aller ?" /><span className="shortcut">⌘ K</span></div><div className="hero-meta"><span>🌍 Depuis <b>Cameroun</b></span><span className="dot">•</span><span>Dernière mise à jour : <b>14 sept. 2026</b></span></div></div><div className="hero-art"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="globe">✈</div><div className="float-card card-one">🇨🇲 <b>Cameroun</b><small>Passeport sélectionné</small></div><div className="float-card card-two"><span className="check">✓</span><b>Source officielle</b><small>Vérifiée il y a 2 jours</small></div></div></section>
    <section className="stats"><div><strong>198</strong><span>passeports suivis</span></div><div><strong>227</strong><span>destinations</span></div><div><strong>38 612</strong><span>règles référencées</span></div><div><strong>100%</strong><span>sources transparentes</span></div><div className="stat-note">Les règles changent.<br /><b>Nous vous prévenons.</b> <span>→</span></div></section>
    <section className="workspace"><div className="section-heading"><div><span className="eyebrow">VOTRE CARTE DE MOBILITÉ</span><h2>Où pouvez-vous aller ?</h2></div><div className="view-toggle"><button className="selected">▦ Carte</button><button>☷ Liste</button></div></div><div className="map-layout"><div className="map"><div className="map-toolbar"><button>−</button><button>＋</button><button>⌖</button><span>Votre passeport : <b>🇨🇲 Cameroun</b></span></div><div className="map-grid" aria-label="Carte interactive des destinations"><div className="continent africa">✦</div><div className="continent europe">◌</div><div className="continent asia">⌁</div>{[['🇷🇼','Rwanda','green',49,58],['🇰🇪','Kenya','blue',55,63],['🇫🇷','France','red',47,35],['🇹🇷','Turquie','red',56,39],['🇦🇪','UAE','amber',66,49],['🇲🇦','Maroc','amber',39,43]].map(([f,n,c,x,y]) => <button key={String(n)} className={'map-pin '+c} style={{left:`${x}%`,top:`${y}%`}} onClick={() => setSelected(destinations.find(d => d.name.startsWith(String(n).split(' ')[0])) || destinations[0])}><span>{f}</span><small>{n}</small></button>)}</div><div className="legend"><span><i className="green"/> Sans visa / arrivée</span><span><i className="blue"/> Autorisation en ligne</span><span><i className="amber"/> Visa requis</span></div></div><aside className="side-panel"><div className="panel-top"><span className="eyebrow">DESTINATIONS POPULAIRES</span><button>Voir tout →</button></div>{filtered.slice(0,5).map(d => <button className="destination" key={d.name} onClick={() => setSelected(d)}><span className="country-flag">{d.flag}</span><span className="destination-info"><b>{d.name}</b><small>{d.status} · {d.days}</small></span><span className={'status-dot '+d.color} /></button>)}{filtered.length === 0 && <p className="empty">Aucune destination trouvée.</p>}<button className="compare-cta" onClick={() => setTab('Comparer')}><span>⊞</span><div><b>Comparer deux passeports</b><small>Voyez ce qui change en un clin d’œil</small></div><span>→</span></button></aside></div></section>
    <section className="lower"><div className="lower-heading"><div><span className="eyebrow">PRÉPARER, PAS DEVINER</span><h2>Votre prochain voyage, étape par étape.</h2></div><button className="outline">Voir tous les guides →</button></div><div className="feature-grid"><article className="feature-card checklist"><span className="feature-icon">✓</span><h3>Checklists personnalisées</h3><p>Les documents exacts, adaptés à votre nationalité et votre destination.</p><a onClick={() => setSelected(destinations[3])}>Construire ma checklist <span>↗</span></a><div className="paper"><div className="paper-line"/><div className="paper-line short"/><div className="paper-check">✓</div><div className="paper-line"/><div className="paper-line medium"/></div></article><article className="feature-card guide"><span className="feature-icon">◎</span><h3>Guides qui vont au bout</h3><p>Du premier clic au passeport tamponné. Sans jargon, sans zone grise.</p><a onClick={() => setTab('Guides')}>Explorer les guides <span>↗</span></a><div className="guide-art">90<span>/</span>180<small>JOURS SCHENGEN</small></div></article><article className="feature-card alerts"><span className="feature-icon">⌁</span><h3>Des règles qui changent ?</h3><p>Recevez une alerte dès qu’une condition évolue pour votre passeport.</p><a onClick={() => setSaved(!saved)}>{saved ? 'Alerte activée ✓' : 'Activer une alerte'} <span>↗</span></a><div className="alert-art"><span>●</span><span>●</span><span>●</span></div></article></div></section>
    <footer><div className="brand"><span className="brand-mark">P</span><span>passportly</span></div><span>La clarté avant le départ.</span><div><a>Données</a><a>À propos</a><a>Contact</a></div></footer>
    {selected && <div className="modal-backdrop" onClick={() => setSelected(null)}><div className="modal" onClick={e => e.stopPropagation()}><button className="close" onClick={() => setSelected(null)}>×</button><div className="modal-title"><span>{selected.flag}</span><div><span className="eyebrow">DEPUIS LE CAMEROUN</span><h2>{selected.name}</h2></div></div><div className={'visa-status '+selected.color}><span>●</span><div><b>{selected.status}</b><small>{selected.days} · mise à jour le {selected.checked}</small></div></div><div className="modal-grid"><div><span className="eyebrow">À PRÉVOIR</span><ul>{selected.steps.map(s => <li key={s}><span>✓</span>{s}</li>)}</ul></div><div className="facts"><div><small>COÛT ESTIMÉ</small><b>{selected.fee}</b></div><div><small>CONFIANCE</small><b>{selected.confidence}</b></div></div></div><div className="source">◉ Source : <b>{selected.source}</b><span>↗</span></div><button className="primary">Créer ma checklist <span>→</span></button></div></div>}
  </main>;
}
