'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ProductPanels } from './components/ProductPanels';
type Destination={code:string;name:string;status:string;requirement:string;days:string;color:string;source?:string;checked?:string;confidence?:string};
function Flag({code,fallback}:{code:string;fallback:string}){return <span className="flag-image"><img src={`/flags/${code}.svg`} alt={fallback}/><span>{fallback}</span></span>}
function Row({d,onClick}:{d:Destination;onClick:()=>void}){return <button className="destination" onClick={onClick}><span className="country-flag"><Flag code={d.code} fallback={d.code.toUpperCase()}/></span><span className="destination-info"><b>{d.name} <small className="country-code">{d.code.toUpperCase()}</small></b><small>{d.status} · {d.days}</small></span><span className={'status-dot '+d.color}/></button>}
export default function Home(){
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[view,setView]=useState<'map'|'list'>('map'),[tab,setTab]=useState('Explorer'),[countries,setCountries]=useState<Destination[]>([]),[selected,setSelected]=useState<Destination|null>(null),[loading,setLoading]=useState(true);
 useEffect(()=>{const c=new AbortController();setLoading(true);fetch(`/api/countries?passport=CM&requirement=${filter}&search=${encodeURIComponent(query)}`,{signal:c.signal}).then(r=>r.json()).then(j=>setCountries(j.data||[])).catch(()=>{}).finally(()=>setLoading(false));return()=>c.abort()},[filter,query]);
 return <main><header className="topbar"><Link className="brand" href="/"><span className="brand-mark">P</span><span>passportly</span></Link><nav>{['Explorer','Guides','Comparer','API'].map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</nav><div className="top-actions"><button className="language">FR <span>⌄</span></button><Link className="login" href="/account">Se connecter</Link><button className="menu">☰</button></div></header>
 <section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="pulse"/> DONNÉES VÉRIFIÉES, VOYAGES ÉCLAIRÉS</div><h1>Le monde est grand.<br/><em>Votre passeport aussi.</em></h1><p>Comprenez les règles, préparez vos documents et partez avec une longueur d’avance.</p><div className="searchbar"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Où voulez-vous aller ?"/><span className="shortcut">⌘ K</span></div><div className="hero-meta"><span>🌍 Depuis <b>Cameroun</b></span><span>•</span><span>Règles synchronisées depuis PostgreSQL</span></div></div><div className="hero-art"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="globe">✈</div><div className="float-card card-one"><Flag code="cm" fallback="CM"/> <b>Cameroun</b><small>Passeport sélectionné</small></div></div></section>
 <ProductPanels tab={tab}/><section className="stats"><div><strong>198</strong><span>passeports suivis</span></div><div><strong>{countries.length||'—'}</strong><span>destinations chargées</span></div><div><strong>38 612</strong><span>règles référencées</span></div><div><strong>100%</strong><span>sources transparentes</span></div></section>
 <section className="workspace"><div className="section-heading"><div><span className="eyebrow">VOTRE CARTE DE MOBILITÉ</span><h2>Où pouvez-vous aller ?</h2></div><div className="view-toggle"><button className={view==='map'?'selected':''} onClick={()=>setView('map')}>▦ Carte</button><button className={view==='list'?'selected':''} onClick={()=>setView('list')}>☷ Liste</button></div></div><div className="explorer-filters">{[['all','Toutes'],['visa_free','Sans visa'],['evisa','eVisa'],['visa_on_arrival','À l’arrivée'],['visa_required','Requis']].map(([k,l])=><button key={k} className={filter===k?'active':''} onClick={()=>setFilter(k)}>{l}</button>)}</div>{loading?<p className="empty">Chargement des destinations…</p>:view==='list'?<div className="country-list">{countries.map(d=><Row key={d.code} d={d} onClick={()=>setSelected(d)}/>)}</div>:<div className="map-layout"><div className="map"><div className="map-toolbar"><button>−</button><button>＋</button><button>⌖</button><span>Votre passeport : <Flag code="cm" fallback="CM"/> <b>Cameroun</b></span></div><div className="map-grid" aria-label="Carte des destinations"><div className="continent africa">✦</div><div className="continent europe">◌</div><div className="continent asia">⌁</div>{countries.slice(0,12).map((d,i)=><button key={d.code} className={'map-pin '+d.color} style={{left:`${35+(i*17)%42}%`,top:`${30+(i*23)%42}%`}} onClick={()=>setSelected(d)}><span><Flag code={d.code} fallback={d.code.toUpperCase()}/></span><small>{d.name}</small></button>)}</div><div className="legend"><span><i className="green"/> Sans visa / arrivée</span><span><i className="blue"/> Autorisation en ligne</span><span><i className="amber"/> Visa requis</span></div></div><aside className="side-panel"><div className="panel-top"><span className="eyebrow">DESTINATIONS POPULAIRES</span><button onClick={()=>setView('list')}>Voir tout →</button></div>{countries.slice(0,5).map(d=><Row key={d.code} d={d} onClick={()=>setSelected(d)}/>)}{!countries.length&&<p className="empty">Aucune destination trouvée.</p>}<button className="compare-cta" onClick={()=>setTab('Comparer')}><span>⊞</span><div><b>Comparer deux passeports</b><small>Voyez ce qui change en un clin d’œil</small></div><span>→</span></button></aside></div>}</section>
 <footer><div className="brand"><span className="brand-mark">P</span><span>passportly</span></div><span>La clarté avant le départ.</span></footer>{selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><div className="modal-title"><Flag code={selected.code} fallback={selected.code.toUpperCase()}/><div><span className="eyebrow">DEPUIS LE CAMEROUN · {selected.code.toUpperCase()}</span><h2>{selected.name}</h2></div></div><div className={'visa-status '+selected.color}><span>●</span><div><b>{selected.status}</b><small>{selected.days} · mise à jour le {selected.checked||'non renseignée'}</small></div></div><div className="modal-grid"><div><span className="eyebrow">INFORMATIONS</span><ul><li><span>✓</span>Règle alimentée par PostgreSQL</li><li><span>✓</span>Code pays : {selected.code.toUpperCase()}</li><li><span>✓</span>Vérifier les conditions avant le départ</li></ul></div><div className="facts"><div><small>SOURCE</small><b>{selected.source||'Dataset'}</b></div><div><small>CONFIANCE</small><b>{selected.confidence||'Dataset'}</b></div></div></div><div className="source">◉ Source : <b>{selected.source||'Base PostgreSQL'}</b></div></div></div>}</main>;
}
