import { escapeHtml as e } from '../../shared/lib/html';

const nav = [['/','Explorer'],['/visa','Visa'],['/assistant','Préparer un dossier'],['/itinerary','Schengen'],['/community','Communauté'],['/developer','API']];
const input = (name:string,label:string,type='text',extra='') => `<label>${label}<input name="${name}" type="${type}" ${extra}></label>`;
const passport = '<label>Votre passeport<select name="passport" data-passports aria-label="Votre passeport"><option value="CM">Cameroun</option></select></label>';
const destination = '<label>Destination<select name="destination" data-destinations aria-label="Destination"><option value="">Choisir une destination</option></select></label>';
const routeFields = `<div class="nova-fields">${passport}${destination}</div>`;
const feedback = '<p role="status" class="nova-feedback" data-feedback></p>';
const section = (title:string,body:string) => `<section class="nova-panel"><h2>${title}</h2>${body}</section>`;
const action = (text:string,attrs='') => `<button ${attrs}>${text}</button>`;

export function publicHeader(screen:string) {
 return `<header class="nova-header"><a class="nova-brand" href="/">Passportly</a><nav aria-label="Navigation principale">${nav.map(([href,label])=>`<a href="${href}" ${screen==='atlas'&&href==='/'?'aria-current="page"':''}>${label}</a>`).join('')}</nav><a href="/account" data-account-link>Mon espace</a></header>`;
}
export function publicFooter() {
 return `<footer class="nova-footer"><div><a class="nova-brand" href="/">Passportly</a><p>Comprendre les règles. Préparer son départ.</p></div><div><h2>Voyager</h2><a href="/">Explorer les destinations</a><a href="/visa">Exigences de visa</a><a href="/assistant">Préparer un dossier</a><a href="/itinerary">Calculateur Schengen</a><a href="/community">Retours d’expérience</a></div><div><h2>Informations</h2><a href="/developer">Documentation API</a><a href="/data-policy">Sources et méthode</a><a href="/privacy">Confidentialité</a><a href="/legal">Mentions légales</a><a href="/account">Compte et alertes</a></div><small>Cartographie : Natural Earth. Règles : Visa Requirements Dataset (CC BY 4.0) et sources indiquées sur chaque fiche.</small></footer>`;
}
export function renderPage(screen:string,request:Request) {
 const url = new URL(request.url);
 const publicPath=request.headers.get('x-passportly-path') || url.pathname;
 let title = '', sub = '', body = '';
 switch(screen) {
 case 'home': case 'atlas':
  title='Le monde, depuis votre passeport.'; sub='Choisissez une nationalité et consultez les conditions de voyage par destination.';
  body = section('Votre recherche',`<form data-route-search action="/visa">${routeFields}${action('Consulter la destination','type="submit"')}${feedback}</form>`)+
   `<div class="nova-toolbar"><label>Rechercher un pays<input id="country-search" type="search" placeholder="Nom ou code du pays"></label><label>Exigence<select id="requirement-filter"><option value="all">Toutes</option><option value="visa_free">Sans visa</option><option value="evisa">Visa électronique</option><option value="eta">Autorisation électronique</option><option value="visa_on_arrival">À l’arrivée</option><option value="visa_required">Visa requis</option><option value="no_admission">Entrée non autorisée</option></select></label>${action('Actualiser','id="refresh-rules" type="button"')}<a href="/compare">Comparer deux passeports</a></div>`+
   `<div class="nova-stats" id="rule-counts" aria-live="polite"></div><div class="nova-map-tools">${action('Agrandir','data-zoom="in" aria-label="Agrandir la carte"')}${action('Réduire','data-zoom="out" aria-label="Réduire la carte"')}${action('Recentrer','data-zoom="reset"')}<a href="#destinations">Voir la liste complète</a></div><div class="nova-map" id="real-world-map" role="region" aria-label="Carte des exigences de visa"></div><p class="nova-muted">La liste inclut aussi les territoires trop petits pour cette échelle cartographique.</p><section id="destinations"><h2>Destinations</h2><p id="rules-status" role="status">Chargement des règles…</p><div class="nova-country-grid" id="country-results"></div></section>`; break;
 case 'visa':
  title='Les conditions de votre voyage.';sub='Passeport ordinaire, tourisme et arrivée directe. Les autres motifs peuvent avoir des exigences différentes.';
  body=section('Choisir un trajet',`<form data-route-search>${routeFields}${action('Consulter','type="submit"')}${feedback}</form>`)+`<div id="visa-result" aria-live="polite"></div>`;break;
 case 'assistant':
  title='Votre dossier, étape par étape.'; sub='Une liste de préparation personnelle, à compléter avec les exigences du portail officiel de votre destination.';
  body=section('Votre voyage',`<form data-route-search>${routeFields}${action('Préparer','type="submit"')}${feedback}</form>`)+`<div id="visa-result" aria-live="polite"></div>`+
   section('Votre checklist',`<p>Les éléments ci-dessous sont des tâches de préparation, pas une liste de pièces exigées par un consulat.</p><form id="checklist-form"><div id="checklist-items"></div><div class="nova-fields">${input('task','Ajouter une tâche personnelle')}${action('Ajouter','type="button" id="add-task"')}</div>${action('Sauvegarder dans mon compte','type="submit"')}${action('Imprimer / enregistrer en PDF','type="button" data-print')}${feedback}</form>`);break;
 case 'schengen':
  title='Votre calendrier Schengen.'; sub='Calculez les jours passés dans la fenêtre des 180 jours précédant une date donnée. Les jours d’entrée et de sortie sont inclus.';
  body=section('Vos séjours',`<form id="schengen-form">${input('referenceDate','Date de contrôle','date','required')}<div id="stay-rows"></div>${action('Ajouter un séjour','type="button" id="add-stay"')}${action('Calculer','type="submit"')}${feedback}</form><p><a href="https://home-affairs.ec.europa.eu/policies/schengen/border-crossing/short-stay-calculator_en" target="_blank" rel="noopener noreferrer">Consulter la règle et le calculateur de la Commission européenne</a></p>`)+`<div id="schengen-result" aria-live="polite"></div>`+section('Conserver le calcul',`${action('Sauvegarder dans mon compte','type="button" id="save-itinerary" disabled')}${action('Imprimer / enregistrer en PDF','type="button" data-print')}<p role="status" id="itinerary-feedback"></p>`);break;
 case 'community':
  title='Le carnet des voyageurs.'; sub='Les expériences publiées sont relues avant leur mise en ligne. Elles ne remplacent pas les informations officielles.';
  body=section('Partager mon expérience',`<form id="testimonial-form">${input('name','Nom affiché','text','required maxlength="100"')}${input('destination','Destination','text','required maxlength="100"')}<label>Votre retour<textarea name="content" required maxlength="1000" rows="5"></textarea></label><label>Votre appréciation<select name="rating"><option value="5">5 / 5</option><option value="4">4 / 5</option><option value="3">3 / 5</option><option value="2">2 / 5</option><option value="1">1 / 5</option></select></label>${action('Soumettre pour modération','type="submit"')}${feedback}</form>`)+`<section><h2>Expériences publiées</h2><label>Rechercher<input type="search" id="community-search" placeholder="Destination ou mot-clé"></label><div id="community-feed" aria-live="polite"></div></section>`;break;
 case 'dashboard':
  title='Votre espace personnel.';sub='Vos destinations, vos alertes et vos préparations enregistrées.';
  body=`<p id="account-status" role="status">Chargement de votre compte…</p>${action('Se déconnecter','id="logout" type="button"')}`+
   `<div class="nova-columns">${section('Destinations enregistrées',`<form id="saved-form">${routeFields}${action('Enregistrer','type="submit"')}${feedback}</form><div id="saved-list"></div>`)}${section('Trajets suivis',`<p>Retrouvez ici les changements publiés dans la base pour les trajets que vous suivez.</p><form id="alert-form">${routeFields}${action('Suivre ce trajet','type="submit"')}${feedback}</form><div id="alerts-list"></div>`)}</div>`+
   section('Mes checklists','<div id="account-checklists"></div>')+section('Mes calculs Schengen','<div id="account-itineraries"></div>')+section('Mes témoignages','<div id="account-testimonials"></div>')+section('Mes données',`${action('Exporter mes données','type="button" id="export-account"')}${action('Supprimer mon compte','type="button" id="delete-account"')}<p role="status" id="privacy-feedback"></p>`);break;
 case 'auth':
  title=publicPath==='/register'?'Créez votre compte.':'Bon retour.';sub='Retrouvez vos destinations et vos listes de préparation.';
  body=`<div class="nova-auth"><section class="nova-panel"><div class="nova-toolbar"><button type="button" data-auth-mode="login">Se connecter</button><button type="button" data-auth-mode="register">Créer un compte</button></div><form id="auth-form" data-mode="${publicPath==='/register'?'register':'login'}">${input('email','Email','email','required autocomplete="email"')}${input('password','Mot de passe','password','required minlength="8" maxlength="128" autocomplete="current-password"')}${action('Continuer','type="submit"')}${feedback}</form><p>Vos informations de connexion restent privées.</p></section></div>`;break;
 case 'developer':
  title='Les règles de visa dans vos produits.';sub='Une API qui indique les données disponibles, leur provenance et leur date de vérification lorsqu’elle existe.';
  body=section('Documentation',`<p>Authentification par l’en-tête <code>x-api-key</code>. Les limites actuellement appliquées sont horaires.</p><a href="/api/v1/openapi.json">Télécharger OpenAPI</a><pre>GET /api/v1/visa?passport=CM&amp;destination=FR\nx-api-key: VOTRE_CLE</pre><p>Clé gratuite : 100 requêtes par heure. Le statut d’une règle n’est pas une garantie d’admission.</p>`)+
   section('Mes clés API',`<form id="api-key-form">${input('name','Nom de la clé','text','required maxlength="100"')}${action('Créer une clé gratuite','type="submit"')}${feedback}</form><div id="new-api-key"></div><div id="api-key-list"></div>`)+
   section('Tester une requête',`<form id="api-test-form">${routeFields}${input('key','Clé API','password','required autocomplete="off"')}${action('Exécuter','type="submit"')}${feedback}</form><pre id="api-test-result"></pre>`);break;
 case 'compare':
  title='Deux passeports, côte à côte.';sub='Comparez les exigences enregistrées pour une même destination.';
  body=section('Vos passeports',`<form id="compare-form"><div class="nova-fields">${passport}<label>Comparer avec<select name="right" data-passports><option value="FR">France</option></select></label></div>${action('Comparer','type="submit"')}${feedback}</form>`)+`<div id="comparison-result"></div>`;break;
 case 'resources':
  title='Les portails à consulter.';sub='Ces liens ouvrent les sites des autorités compétentes. Ils ne constituent pas une validation de votre éligibilité.';
  body=section('Portails officiels',`<div class="nova-country-grid">${[['France','https://france-visas.gouv.fr/'],['Canada','https://www.canada.ca/fr/immigration-refugies-citoyennete/services/visiter-canada.html'],['Royaume-Uni','https://www.gov.uk/check-uk-visa'],['États-Unis','https://travel.state.gov/content/travel/en/us-visas.html'],['Turquie','https://www.evisa.gov.tr/'],['Émirats arabes unis','https://u.ae/en/information-and-services/visa-and-emirates-id']].map(([name,href])=>`<a class="nova-country" href="${href}" target="_blank" rel="noopener noreferrer"><h3>${name}</h3>Consulter le portail officiel</a>`).join('')}</div>`);break;
 case 'data-policy':
  title='Sources et méthode.';sub='Une règle enregistrée et une règle vérifiée sont deux choses différentes.';
  body=section('Origine des règles','<p>La matrice de départ provient du <a href="https://github.com/maxix7/visa-requirements-dataset" target="_blank" rel="noopener noreferrer">Visa Requirements Dataset</a>, sous licence CC BY 4.0. Son socle est un instantané ; seules certaines corrections comportent une page primaire et une date de vérification.</p><p>Sur chaque fiche, nous affichons la référence enregistrée et la date lorsqu’elle existe. Une référence au dataset n’est pas présentée comme une vérification gouvernementale.</p>')+section('Périmètre','<p>Les règles portent sur les passeports ordinaires, les voyages touristiques et les arrivées directes. Elles ne couvrent pas les exceptions liées à un titre de séjour, le transit, les études ou le travail.</p><p>Les frais, délais réels, taux de refus et pièces exigées ne sont pas inventés pour compléter une fiche.</p>')+section('Mises à jour','<p>La recherche consulte la base de données à chaque chargement et lors de l’actualisation. Cela ne signifie pas que chaque autorité est surveillée en continu. Les changements de règles nécessitent une collecte et une validation avant leur publication.</p><p>La carte utilise les limites géographiques de <a href="https://www.naturalearthdata.com/" target="_blank" rel="noopener noreferrer">Natural Earth</a>, domaine public.</p>');break;
 case 'privacy':
  title='Confidentialité.';sub='Les données nécessaires à votre espace personnel.';
  body=section('Données enregistrées','<p>Votre compte contient votre email, un mot de passe haché, vos destinations, vos suivis, vos checklists, vos calculs et les témoignages que vous soumettez. Un cookie HTTP-only maintient votre session.</p><p>Le choix du passeport et les listes personnelles non sauvegardées peuvent être conservés localement dans votre navigateur.</p>')+section('Exporter ou supprimer','<p>Vous pouvez exporter les informations de votre compte et demander sa suppression depuis <a href="/account">votre espace</a>. La publication d’un témoignage est soumise à modération. Une clé API révoquée n’autorise plus les requêtes.</p>');break;
 case 'legal': case 'terms':
  title='À propos de Passportly.';sub='Un outil d’information et de préparation au voyage.';
  body=section('Service','<p>Passportly aide à consulter les règles enregistrées et à organiser une préparation personnelle. Il ne délivre pas de visa, ne représente pas un consulat et ne garantit pas l’admission à une frontière.</p><p>Le site est hébergé par Render et sa base de données par Neon.</p>')+section('Avant votre départ','<p>Les conditions applicables doivent être confirmées auprès de l’autorité compétente. Une checklist personnelle ou un calcul ne remplace pas la décision d’une administration.</p><a href="/data-policy">Consulter les sources et limites</a>');break;
 default:title='Page introuvable';
 }
 return `<main class="nova-main" data-screen="${e(screen)}"><div class="nova-intro"><p class="nova-kicker">Passportly</p><h1>${title}</h1><p>${sub}</p></div>${body}</main>`;
}
