export type GuideStep = { title: string; detail: string };
export type Guide = {
  slug: string; country: string; code: string; flag: string; kicker: string;
  summary: string; stay: string; fee: string; delay: string; updated: string;
  sourceName: string; sourceUrl: string; documents: string[]; steps: GuideStep[];
};

const common = (country: string): GuideStep[] => [
  { title: 'Vérifier les conditions d’entrée', detail: `Confirmez les règles propres au passeport camerounais sur le site officiel de ${country}.` },
  { title: 'Réunir les justificatifs', detail: 'Préparez des copies lisibles et des traductions lorsque le consulat les demande.' },
  { title: 'Déposer la demande', detail: 'Utilisez le portail officiel ou le prestataire indiqué par l’autorité compétente.' },
  { title: 'Suivre et conserver la décision', detail: 'Gardez le reçu, le numéro de dossier et la décision jusqu’au retour.' },
];

export const guides: Guide[] = [
  { slug: 'schengen', country: 'Espace Schengen', code: 'fr', flag: '🇪🇺', kicker: 'Court séjour · 27 pays', summary: 'Le dossier Schengen expliqué simplement, de France-Visas au retrait du passeport.', stay: '90 jours sur 180', fee: '90 € + frais de service', delay: '15 jours en moyenne', updated: '14 sept. 2026', sourceName: 'France-Visas', sourceUrl: 'https://france-visas.gouv.fr/', documents: ['Passeport valide 3 mois après la sortie', 'Formulaire et récépissé France-Visas', 'Assurance voyage Schengen (30 000 €)', 'Réservations transport et hébergement', 'Preuves de ressources et d’attaches'], steps: [{ title: 'Créer le dossier France-Visas', detail: 'Remplissez le formulaire en ligne et imprimez le récépissé.' }, { title: 'Réserver un rendez-vous', detail: 'Choisissez le centre indiqué pour votre lieu de résidence.' }, ...common('France'), { title: 'Respecter la règle 90/180', detail: 'Le séjour cumulé ne peut pas dépasser 90 jours sur toute période glissante de 180 jours.' }] },
  { slug: 'canada', country: 'Canada', code: 'ca', flag: '🇨🇦', kicker: 'Visiteur · tourisme', summary: 'Les étapes pour préparer une demande de visa visiteur canadien depuis le Cameroun.', stay: 'Jusqu’à 6 mois', fee: '100 CAD + biométrie', delay: 'Variable selon le centre', updated: '14 sept. 2026', sourceName: 'Immigration, Réfugiés et Citoyenneté Canada', sourceUrl: 'https://www.canada.ca/fr/immigration-refugies-citoyennete/services/visiter-canada.html', documents: ['Passeport et historique de voyages', 'Relevés bancaires récents', 'Lettre d’invitation ou itinéraire', 'Preuves d’emploi et d’attaches', 'Photo et biométrie'], steps: common('Canada') },
  { slug: 'royaume-uni', country: 'Royaume-Uni', code: 'gb', flag: '🇬🇧', kicker: 'Standard Visitor visa', summary: 'Préparez votre visa visiteur britannique avec un dossier lisible et cohérent.', stay: 'Jusqu’à 6 mois', fee: 'À partir de 127 £', delay: 'Environ 3 semaines', updated: '14 sept. 2026', sourceName: 'GOV.UK', sourceUrl: 'https://www.gov.uk/standard-visitor', documents: ['Passeport valide', 'Formulaire en ligne', 'Relevés bancaires', 'Attestation d’emploi ou d’études', 'Itinéraire et hébergement'], steps: common('GOV.UK') },
  { slug: 'etats-unis', country: 'États-Unis', code: 'us', flag: '🇺🇸', kicker: 'Visite · affaires · B1/B2', summary: 'Comprendre le DS-160, le rendez-vous et l’entretien consulaire américain.', stay: 'Selon décision consulaire', fee: '185 USD', delay: 'Selon disponibilité', updated: '14 sept. 2026', sourceName: 'U.S. Department of State', sourceUrl: 'https://travel.state.gov/content/travel/en/us-visas/tourism-visit/visitor.html', documents: ['Passeport', 'Confirmation DS-160', 'Reçu de paiement', 'Photo conforme', 'Preuves du motif et du retour'], steps: common('l’ambassade des États-Unis') },
  { slug: 'turquie', country: 'Turquie', code: 'tr', flag: '🇹🇷', kicker: 'Tourisme · e-Visa', summary: 'Vérifiez l’éligibilité à l’e-Visa et préparez l’alternative consulaire.', stay: 'Jusqu’à 90 jours', fee: 'Variable selon nationalité', delay: 'Immédiat à quelques jours', updated: '14 sept. 2026', sourceName: 'e-Visa République de Türkiye', sourceUrl: 'https://www.evisa.gov.tr/', documents: ['Passeport valide', 'Billet ou itinéraire', 'Réservation d’hébergement', 'Carte bancaire pour le paiement'], steps: common('la Turquie') },
  { slug: 'emirats-arabes-unis', country: 'Émirats arabes unis', code: 'ae', flag: '🇦🇪', kicker: 'Dubaï · Abu Dhabi', summary: 'Les options de visa touristique, le sponsor et les contrôles à l’arrivée.', stay: '30 ou 60 jours', fee: 'Environ 70–150 USD', delay: '2 à 5 jours ouvrés', updated: '14 sept. 2026', sourceName: 'UAE Government Portal', sourceUrl: 'https://u.ae/en/information-and-services/visa-and-emirates-id', documents: ['Passeport valide 6 mois', 'Photo d’identité', 'Billet retour', 'Réservation d’hôtel ou sponsor'], steps: common('l’administration des Émirats') },
  { slug: 'chine', country: 'Chine', code: 'cn', flag: '🇨🇳', kicker: 'Visa tourisme · L', summary: 'Préparez un dossier de visa chinois complet et adapté à votre itinéraire.', stay: 'Selon visa délivré', fee: 'Selon type et nombre d’entrées', delay: 'Environ 4 à 10 jours ouvrés', updated: '14 sept. 2026', sourceName: 'Chinese Visa Application Service Center', sourceUrl: 'https://www.visaforchina.cn/', documents: ['Passeport et formulaire', 'Photo conforme', 'Réservations de vols et hôtels', 'Itinéraire détaillé', 'Justificatifs financiers'], steps: common('la Chine') },
  { slug: 'maroc', country: 'Maroc', code: 'ma', flag: '🇲🇦', kicker: 'Tourisme · court séjour', summary: 'Les documents à anticiper avant un séjour touristique au Maroc.', stay: 'Jusqu’à 90 jours', fee: 'Selon nationalité et visa', delay: 'Selon consulat', updated: '14 sept. 2026', sourceName: 'Accès Maroc', sourceUrl: 'https://www.acces-maroc.ma/', documents: ['Passeport valide', 'Billet retour', 'Hébergement', 'Preuves de moyens suffisants'], steps: common('l’administration marocaine') },
  { slug: 'rwanda', country: 'Rwanda', code: 'rw', flag: '🇷🇼', kicker: 'eVisa · arrivée', summary: 'Faire sa demande en ligne et connaître les formalités d’entrée au Rwanda.', stay: 'Jusqu’à 30 jours', fee: 'Environ 50 USD', delay: 'Jusqu’à 7 jours', updated: '14 sept. 2026', sourceName: 'Directorate General of Immigration and Emigration', sourceUrl: 'https://www.migration.gov.rw/', documents: ['Passeport valide 6 mois', 'Photo ou scan du passeport', 'Adresse de séjour', 'Billet retour'], steps: common('l’immigration rwandaise') },
  { slug: 'kenya', country: 'Kenya', code: 'ke', flag: '🇰🇪', kicker: 'eTA obligatoire', summary: 'Obtenir l’autorisation électronique de voyage avant le départ pour le Kenya.', stay: 'Selon autorisation', fee: 'Environ 35 USD', delay: '3 jours ouvrés recommandés', updated: '14 sept. 2026', sourceName: 'Kenya eTA', sourceUrl: 'https://www.etakenya.go.ke/', documents: ['Passeport valide 6 mois', 'Photo portrait', 'Réservation d’hébergement', 'Billet retour ou itinéraire', 'Carte bancaire'], steps: common('Kenya eTA') },
];

export function getGuide(slug: string) { return guides.find((guide) => guide.slug === slug); }
